# Generated by Django 4.2 on 2023-06-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_remove_chatroom_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'verbose_name': 'Комната', 'verbose_name_plural': 'Список комнат'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('timestamp',), 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Список сообщений'},
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время'),
        ),
    ]
