# Generated by Django 4.2 on 2023-06-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='member_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество участников'),
        ),
    ]
