# Dockerfile
FROM node:19-alpine as builder

# create destination directory
RUN mkdir -p /home/react_app
WORKDIR /home/react_app

# update and install dependency
RUN apk update && apk upgrade
RUN apk add git

# copy the app, note .dockerignore
COPY . /home/react_app/
RUN npm install 
# RUN npm run build
